### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by gdzanell** [cse442-fall-2019-offering/442projects-katz#1]
As student/faculty I want to be able to login to so I can be the only one to access my profile.

**Comment by gdzanell** [comment]
Acceptance Test:
- [ ] Able to add account name into an account name box
- [ ] Able to add account name into a password box
- [ ] Able to login if both password and username match
- [ ] Redirects user to profile page when logged in

**Comment by vtattyba** [comment]
- [ ] Able to login if both password and username match
->Justification: I removed this because for this to work you need to store the person information on the database and we don’t need that for our first sprint.
