### ISSUE TITLE
Class Page Template

### ISSUE THREAD

**Issue by igorkuzm** [cse442-fall-2019-offering/442projects-katz#19]
Class page to have an overview of the class.

Task Test:
1. The page has a profile dash on top, and tabs for Home and profile page.
2. Couse has tabs that direct to Create a Team, Available Teams, and Available People
3. Available People allows you to click on them and view the profile page.
4. Create a Team has a text box to enter a name

**Comment by gdzanell** [comment]
Class page to have an overview of the class.

Task Test:
1. Open class page through the home page.
2. The page has a profile dash on top, and tabs for Home and profile page.
3. Couse has tabs that direct to Create a Team, Available Teams, and Available People
4. Available People allows you to click on them and view the profile page.
5. Create a Team has a text box to enter a name
