### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by gdzanell** [cse442-fall-2019-offering/442projects-katz#2]
As faculty/student I want to be able to create an account for myself so I can access the website.

**Comment by gdzanell** [comment]
- [ ] The home page has a button to create account
- [ ] When clicked the button redirects one to create account page
- [ ] Can enter an email address on create account page
- [ ] Can create a password on create account page
- [ ] Password has to be entered twice to check if matching
- [ ] Verification email is sent went creat account button is pressed

**Comment by vtattyba** [comment]
- [ ] Verification email is sent went create account button is pressed
Comment: REMOVED, This is a sprint 2 type of thing
