### ISSUE TITLE
Team Page Template

### ISSUE THREAD

**Issue by igorkuzm** [cse442-fall-2019-offering/442projects-katz#20]
Team page to have an overview of team

Task Test:
1. The page has a profile dash on top, and tabs for home and profile page.
2. On the left contains team functionality GUI for Kick, Leave, Add and close group
3. The page shows the description of the team, skills needed for project and members

**Comment by gdzanell** [comment]
Team page to have an overview of team

Task Test:
1.Open team page through the homepage
2. The page has a profile dash on top, and tabs for home and profile page.
3. On the left contains team functionality GUI for Kick, Leave, Add and close group
4. The page shows the description of the team, skills needed for project and members
